// Mocks generated by Mockito 5.0.13 from annotations
// in instapic/test/redux/middlewares/middlewares_fetch_posts_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:instapic/remote/api.dart' as _i4;
import 'package:instapic/remote/response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDio extends _i1.Fake implements _i2.Dio {}

class _FakeApiResponse extends _i1.Fake implements _i3.ApiResponse {}

/// A class which mocks [Api].
///
/// See the documentation for Mockito's code generation for more information.
class MockApi extends _i1.Mock implements _i4.Api {
  MockApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio())
          as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(Invocation.setter(#dio, _dio),
      returnValueForMissingStub: null);
  @override
  String getErrorMsg(Object? e, int? statusCode) =>
      (super.noSuchMethod(Invocation.method(#getErrorMsg, [e, statusCode]),
          returnValue: '') as String);
  @override
  _i5.Future<_i3.ApiResponse> signUp(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#signUp, [username, password]),
              returnValue: Future<_i3.ApiResponse>.value(_FakeApiResponse()))
          as _i5.Future<_i3.ApiResponse>);
  @override
  _i5.Future<_i3.ApiResponse> signIn(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#signIn, [username, password]),
              returnValue: Future<_i3.ApiResponse>.value(_FakeApiResponse()))
          as _i5.Future<_i3.ApiResponse>);
  @override
  _i5.Future<_i3.ApiResponse> signInQuery() =>
      (super.noSuchMethod(Invocation.method(#signInQuery, []),
              returnValue: Future<_i3.ApiResponse>.value(_FakeApiResponse()))
          as _i5.Future<_i3.ApiResponse>);
  @override
  _i5.Future<_i3.ApiResponse> logOut() =>
      (super.noSuchMethod(Invocation.method(#logOut, []),
              returnValue: Future<_i3.ApiResponse>.value(_FakeApiResponse()))
          as _i5.Future<_i3.ApiResponse>);
  @override
  _i5.Future<_i3.ApiResponse> post(
          _i6.Uint8List? imageBytes, String? description, String? imageFileName,
          {void Function(int, int)? onSendProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [imageBytes, description, imageFileName],
                  {#onSendProgress: onSendProgress}),
              returnValue: Future<_i3.ApiResponse>.value(_FakeApiResponse()))
          as _i5.Future<_i3.ApiResponse>);
  @override
  _i5.Future<_i3.ApiResponse> posts(
          {int? start = 0,
          int? limit = 10,
          String? username,
          String? sortby,
          String? order}) =>
      (super.noSuchMethod(
              Invocation.method(#posts, [], {
                #start: start,
                #limit: limit,
                #username: username,
                #sortby: sortby,
                #order: order
              }),
              returnValue: Future<_i3.ApiResponse>.value(_FakeApiResponse()))
          as _i5.Future<_i3.ApiResponse>);
  @override
  String toString() => super.toString();
}
